# Generated by Django 5.0.7 on 2024-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instruction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='rgb(254, 222, 117)', max_length=100)),
            ],
        ),
    ]
